#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          5
bspc focused_border_color "#8ab4f8"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a lutris desktop='^4'
bspc rule -a discord desktop='^5'
bspc rule -a Spotify desktop='^6'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Extra settings
setxkbmap hu &
xsetroot -cursor_name left_ptr &        # Change the default cursor from an X to an arrow

# autostart
picom &
~/.config/polybar/launch.sh &
# nitrogen --restore &
betterlockscreen -w &
blueman-applet &
nm-applet &
~/Alkalmazások/pcloud &
mpv --no-video --volume=70 ~/Zenék/startup.mp3 &
