#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI
bspc monitor -d home web term game chat music

bspc config border_width         2
bspc config window_gap          5
bspc focused_border_color "#8ab4f8"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Ulauncher border=off
bspc rule -a firefox desktop='^2'
bspc rule -a lutris desktop='^4'
bspc rule -a Discord desktop='^5'
bspc rule -a Spotify desktop='^6'
#bspc rule -a Plank layer=above manage=on border=off

# Extra settings
setxkbmap hu &
xsetroot -cursor_name left_ptr &        # Change the default cursor from an X to an arrow

# autostart
picom &
lxpolkit &
~/.config/polybar/launch.sh &
plank &
# nitrogen --restore &
betterlockscreen -w &
blueman-applet &
nm-applet &
flameshot &
~/Alkalmazások/pcloud &
mpv --no-video --volume=70 ~/Zenék/startup.mp3 &
ulauncher --hide-window &
python3 ~/Dokumentumok/Projektek/BingWallpaper/wallpaper.py -l ~/Képek/BingWallpapers
